"""Creating base

Revision ID: f48562251187
Revises: 
Create Date: 2020-06-14 17:53:44.514613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48562251187'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_models',
    sa.Column('model_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('rec_ios', sa.String(), nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('model_id', name=op.f('pk__device_models')),
    sa.UniqueConstraint('model', name=op.f('uq__device_models__model')),
    sa.UniqueConstraint('model_id', name=op.f('uq__device_models__model_id'))
    )
    op.create_table('device_user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk__device_user')),
    sa.UniqueConstraint('username', name=op.f('uq__device_user__username'))
    )
    op.create_table('device_base',
    sa.Column('dev_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('serial_n', sa.String(), nullable=False),
    sa.Column('dev_ios', sa.String(), nullable=False),
    sa.Column('inv_n', sa.String(), nullable=False),
    sa.Column('nom_n', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('power_type', sa.String(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('switch_type', sa.String(), nullable=False),
    sa.Column('place', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=False),
    sa.Column('room', sa.String(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('project', sa.String(), nullable=False),
    sa.Column('in_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['device_models.model_id'], name=op.f('fk__device_base__model_id__device_models')),
    sa.PrimaryKeyConstraint('dev_id', name=op.f('pk__device_base')),
    sa.UniqueConstraint('dev_id', name=op.f('uq__device_base__dev_id'))
    )
    # ### end Alembic commands ###
    op.execute("INSERT INTO device_models (model, rec_ios, power) VALUES ('none','none',0);")
    op.execute(
        "INSERT INTO device_user (username, password, role, columns,search) VALUES ('admin','21232f297a57a5a743894a0e4a801fc3','admin');")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_base')
    op.drop_table('device_user')
    op.drop_table('device_models')
    # ### end Alembic commands ###
