"""empty message

Revision ID: fc2f85a517d1
Revises: f48562251187
Create Date: 2020-06-18 19:00:25.682591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc2f85a517d1'
down_revision = 'f48562251187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__device_base__dev_id'), 'device_base', ['dev_id'])
    op.create_unique_constraint(op.f('uq__device_models__model_id'), 'device_models', ['model_id'])
    op.add_column('device_user', sa.Column('columns', sa.String(), nullable=True))
    op.add_column('device_user', sa.Column('search', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_user', 'search')
    op.drop_column('device_user', 'columns')
    op.drop_constraint(op.f('uq__device_models__model_id'), 'device_models', type_='unique')
    op.drop_constraint(op.f('uq__device_base__dev_id'), 'device_base', type_='unique')
    # ### end Alembic commands ###
