version: '3.2'
services:
    nginx:
        image: 'nginx'
        networks: 
            - webapp-net        
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - '/etc/timezone:/etc/timezone:ro'
            - '/etc/localtime:/etc/localtime:ro'
            - '/usr/web-base/nginx/conf.d:/etc/nginx/conf.d'
            - '/usr/web-base/nginx/ssl:/etc/nginx/ssl'
            - '/usr/web-base/frontend:/frontend'
            - '/usr/web-base/logs/nginx:/logs'
    
    db-pgsql:
        image: 'postgres:12'
        networks: 
            - webapp-net  
        environment:
            - POSTGRES_USER_FILE=/run/secrets/postgres_user
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
            - POSTGRES_DB_FILE=/run/secrets/postgres_db
        ports:
            - "5432:5432"
        volumes:
            - '/etc/timezone:/etc/timezone:ro'
            - '/etc/localtime:/etc/localtime:ro'
            - '/var/lib/postgresql:/var/lib/postgresql'
        secrets:
            - postgres_user
            - postgres_password
            - postgres_db

    db-redis:
        image: 'redis:alpine'
        networks: 
            - webapp-net  
        environment:
            - REDIS_PORT=6379
            - REDIS_PASS_FILE=/run/secrets/redis_password
        ports:
            - "6379:6379"
        volumes:
            - '/var/lib/redis_data:/data'  
        secrets:
            - redis_password
        command: ["sh","-c",'redis-server --requirepass "$$(cat $$REDIS_PASS_FILE)"']

    webapp:
        image: 'webapp'
        networks: 
            - webapp-net               
        volumes:
            - '/etc/timezone:/etc/timezone:ro'
            - '/etc/localtime:/etc/localtime:ro'
            - './app/:/app'
        secrets:
            - postgres_user
            - postgres_password
            - postgres_db
            - snmp_community
            - redis_password
secrets:
    postgres_user:
        external: true    
    postgres_password:
        external: true
    postgres_db:
        external: true
    snmp_community:
        external: true
    redis_password:
        external: true

networks:
    webapp-net:


                
    
